/**
 * Export Service - ส่งออกรายงาน Audit เป็น PDF และ JSON
 */

import { PDFDocument, PDFPage, rgb } from "pdf-lib";
import fs from "fs";
import path from "path";

export interface AuditExportData {
  projectName: string;
  projectSymbol: string;
  description: string;
  chain: string;
  
  // Scores
  githubScore: number;
  tokenomicsScore: number;
  contractRiskScore: number;
  twitterScore: number;
  telegramScore: number;
  discordScore: number;
  overallScore: number;
  riskLevel: string;
  
  // Detailed data
  githubData: any;
  tokenomicsData: any;
  contractRiskData: any;
  socialData: any;
  aiAnalysis: string;
  
  // Metadata
  auditDate: Date;
  auditUrl: string;
}

/**
 * ส่งออกรายงาน Audit เป็น JSON
 */
export function exportToJSON(data: AuditExportData): string {
  const report = {
    metadata: {
      projectName: data.projectName,
      projectSymbol: data.projectSymbol,
      chain: data.chain,
      auditDate: data.auditDate.toISOString(),
      auditUrl: data.auditUrl,
    },
    scores: {
      github: data.githubScore,
      tokenomics: data.tokenomicsScore,
      contractRisk: data.contractRiskScore,
      twitter: data.twitterScore,
      telegram: data.telegramScore,
      discord: data.discordScore,
      overall: data.overallScore,
      riskLevel: data.riskLevel,
    },
    analysis: {
      github: data.githubData,
      tokenomics: data.tokenomicsData,
      contractRisk: data.contractRiskData,
      social: data.socialData,
      aiAnalysis: data.aiAnalysis,
    },
  };

  return JSON.stringify(report, null, 2);
}

/**
 * ส่งออกรายงาน Audit เป็น PDF
 */
export async function exportToPDF(data: AuditExportData): Promise<Buffer> {
  try {
    // สร้าง PDF document
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([612, 792]); // Letter size
    
    const { width, height } = page.getSize();
    const margin = 40;
    let yPosition = height - margin;
    
    // ฟังก์ชันสำหรับเขียนข้อความ
    const drawText = (text: string, fontSize: number = 12, color = rgb(0, 0, 0), bold = false) => {
      page.drawText(text, {
        x: margin,
        y: yPosition,
        size: fontSize,
        color,
      });
      yPosition -= fontSize + 8;
    };

    const drawLine = () => {
      page.drawLine({
        start: { x: margin, y: yPosition },
        end: { x: width - margin, y: yPosition },
        thickness: 1,
        color: rgb(0.8, 0.8, 0.8),
      });
      yPosition -= 16;
    };

    // Header
    drawText(`Crypto Project Audit Report`, 24, rgb(0.2, 0.2, 0.8), true);
    drawText(`${data.projectName} (${data.projectSymbol})`, 18, rgb(0, 0, 0), true);
    yPosition -= 8;
    drawLine();

    // Metadata
    drawText(`Chain: ${data.chain}`, 11);
    drawText(`Audit Date: ${data.auditDate.toLocaleDateString()}`, 11);
    drawText(`Description: ${data.description}`, 11);
    yPosition -= 12;
    drawLine();

    // Overall Score
    drawText(`Overall Score: ${data.overallScore}/100`, 16, rgb(0.2, 0.2, 0.8), true);
    drawText(`Risk Level: ${data.riskLevel.toUpperCase()}`, 12, getRiskColor(data.riskLevel));
    yPosition -= 12;
    drawLine();

    // Individual Scores
    drawText(`Detailed Scores:`, 14, rgb(0, 0, 0), true);
    drawText(`  • GitHub Analysis: ${data.githubScore}/100`, 11);
    drawText(`  • Tokenomics: ${data.tokenomicsScore}/100`, 11);
    drawText(`  • Contract Risk: ${data.contractRiskScore}/100`, 11);
    drawText(`  • Twitter: ${data.twitterScore}/100`, 11);
    drawText(`  • Telegram: ${data.telegramScore}/100`, 11);
    drawText(`  • Discord: ${data.discordScore}/100`, 11);
    yPosition -= 12;
    drawLine();

    // AI Analysis
    drawText(`AI Analysis & Recommendations:`, 14, rgb(0, 0, 0), true);
    
    // Split AI analysis into multiple lines
    const analysisLines = data.aiAnalysis.split("\n");
    for (const line of analysisLines) {
      if (yPosition < margin + 100) {
        // Add new page if running out of space
        const newPage = pdfDoc.addPage([612, 792]);
        yPosition = height - margin;
      }
      
      // Wrap long lines
      const wrappedLines = wrapText(line, 80);
      for (const wrappedLine of wrappedLines) {
        drawText(wrappedLine, 10);
      }
    }

    // Footer
    yPosition = margin;
    drawText(`Generated by Crypto Project Auditor - ${new Date().toISOString()}`, 9, rgb(0.6, 0.6, 0.6));
    drawText(`${data.auditUrl}`, 9, rgb(0.4, 0.4, 0.8));

    // Save PDF to buffer
    const pdfBytes = await pdfDoc.save();
    return Buffer.from(pdfBytes);
  } catch (error) {
    console.error("Error generating PDF:", error);
    throw error;
  }
}

/**
 * ตัดข้อความให้พอดีกับความกว้าง
 */
function wrapText(text: string, maxChars: number): string[] {
  const lines: string[] = [];
  let currentLine = "";

  for (const word of text.split(" ")) {
    if ((currentLine + word).length > maxChars) {
      if (currentLine) lines.push(currentLine.trim());
      currentLine = word;
    } else {
      currentLine += (currentLine ? " " : "") + word;
    }
  }

  if (currentLine) lines.push(currentLine.trim());
  return lines;
}

/**
 * ได้สีตามระดับความเสี่ยง
 */
function getRiskColor(riskLevel: string) {
  switch (riskLevel) {
    case "low":
      return rgb(0.2, 0.8, 0.2); // Green
    case "medium":
      return rgb(0.8, 0.8, 0.2); // Yellow
    case "high":
      return rgb(0.8, 0.4, 0.2); // Orange
    case "critical":
      return rgb(0.8, 0.2, 0.2); // Red
    default:
      return rgb(0, 0, 0); // Black
  }
}
